
DROP TABLE IF EXISTS `USER`;  --用户表
CREATE TABLE `USER` (
  `USER_ID` bigint(16) unsigned zerofill NOT NULL AUTO_INCREMENT,
  `USER_NAME` varchar(20) DEFAULT NULL,
  `USER_PWD` varchar(50) NOT NULL,
  `USER_PHONE` decimal(11,0) DEFAULT NULL,
  `USER_QQ` decimal(20,0) DEFAULT NULL,
  `USER_WECHAT` varchar(50) DEFAULT NULL,
  `USER_EMAIL` varchar(50) DEFAULT NULL,
  `USER_SEX` int(11) DEFAULT NULL,
  `USER_AGE` decimal(3,0) DEFAULT NULL,
  `USER_ADDRESS` varchar(200) DEFAULT NULL,
  `USER_ROLE` int(11) NOT NULL,
  `USER_LEFT_MONEY` decimal(10,2) DEFAULT NULL,
  `USER_REAL_NAME` varchar(20) DEFAULT NULL,
  PRIMARY KEY (`USER_ID`),
  KEY `用户ID` (`USER_ID`) USING HASH
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `EMPLOYEES`; --员工表
CREATE TABLE `EMPLOYEES` (
  `EMPLO_ID` decimal(7,0) NOT NULL,
  `NAME` varchar(20) DEFAULT NULL,
  `SEX` char(1) DEFAULT NULL,
  `AGE` decimal(2,0) DEFAULT NULL,
  `SENIORITY` decimal(2,0) DEFAULT NULL,
  `SALARY` decimal(8,2) DEFAULT NULL,
  `PHONE` varchar(11) DEFAULT NULL,
  `EMAIL` varchar(50) DEFAULT NULL,
  `ADDRESS` varchar(80) DEFAULT NULL,
  `ID_CARD` varchar(25) DEFAULT NULL,
  `QQ` decimal(12,0) DEFAULT NULL,
  `WECHAT` varchar(50) DEFAULT NULL,
  `BIRTHDAY` date DEFAULT NULL,
  `ENTRY_TIME` date DEFAULT NULL,
  `QUIT_TIME` date DEFAULT NULL,
  `DEPARTMENT_ID` decimal(4,0) DEFAULT NULL,
  `POSITION_ID` decimal(4,0) DEFAULT NULL,
  `BOSS_ID` decimal(7,0) DEFAULT NULL,
  PRIMARY KEY (`EMPLO_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `POSITION`; --职位表
CREATE TABLE `POSITION` (
  `POSITION_ID` decimal(5,0) NOT NULL,
  `POSITION_NAME` varchar(10) DEFAULT NULL,
  PRIMARY KEY (`POSITION_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


DROP TABLE IF EXISTS `DEPARTMENT`; --部门表
CREATE TABLE `DEPARTMENT` (
  `DEPARTMENT_ID` decimal(4,0) NOT NULL,
  `DEPARTMENT_NAME` varchar(6) DEFAULT NULL,
  PRIMARY KEY (`DEPARTMENT_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


DROP TABLE IF EXISTS `MENU`; --菜单表
CREATE TABLE `MENU` (
  `MENU_NAME` varchar(50) NOT NULL,
  `MENU_NUM` decimal(2,0) NOT NULL,
  `MENU_VALUE` varchar(20) DEFAULT NULL,
  `MENU_CONTENT` varchar(20) DEFAULT NULL,
  `IS_DISPLAY` char(1) DEFAULT NULL,
  PRIMARY KEY (`MENU_NAME`,`MENU_NUM`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

