
spring:
  application:
    name: lc-kafka
  kafka:
    producer:
      bootstrap-servers: 127.0.0.1:9092
server:
  port: 9011
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/