
server:
  port: 9001
spring:
  application:
    name: lc-quartz
  datasource:
    name: lc-mybatis
    username: root
    url: jdbc:mysql://lc.mysql.com:3306/lc
    password: clz123456
    #url: jdbc:mysql://lc.mysql.com/south
    #password: root
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat,wall,log4j # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    initialSize: 5 # 初始化大小
    maxActive: 20 # 最大
    minIdle: 5 # 最小
    maxWait: 60000 # 配置获取连接等待超时的时间
    timeBetweenEvictionRunsMillis: 60000 # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    minEvictableIdleTimeMillis: 300000 # 配置一个连接在池中最小生存的时间，单位是毫秒
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true # 打开PSCache，并且指定每个连接上PSCache的大小
    maxOpenPreparedStatements: 20 # 打开PSCache，并且指定每个连接上PSCache的大小
    connectionProperties :
      duird:
        stat:
          mergeSql: true
          slowSqlMillis: 5000 # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    useGlobalDataSourceStat: true  #合并多个DruidDataSource的监控数据(暂时不明白时什么意思，也没有测试出来)
      #cachePrepStmts: true  # 开启二级缓存
eureka:
  client:
    service-url:
      defaultZone: http://lc.eureka.com:8761/eureka/,http://lc.eureka.com:8762/eureka/
mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.lc.clz.entity

