spring:
  application:
    name: lc-basic-service
  datasource:
    name: lc-mybatis
    url: jdbc:mysql://lc.mysql.com:3306/lc?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false
    username: root
    password: clz
#    url: jdbc:mysql://127.0.0.1:3306/south
#    username: root
#    password: root
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat,wall,log4j # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    initialSize: 5 # 初始化大小
    maxActive: 20 # 最大
    minIdle: 5 # 最小
    maxWait: 60000 # 配置获取连接等待超时的时间
    timeBetweenEvictionRunsMillis: 60000 # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    minEvictableIdleTimeMillis: 300000 # 配置一个连接在池中最小生存的时间，单位是毫秒
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true # 打开PSCache，并且指定每个连接上PSCache的大小
    maxOpenPreparedStatements: 20 # 打开PSCache，并且指定每个连接上PSCache的大小
    connectionProperties :
      duird:
        stat:
          mergeSql: true
          slowSqlMillis: 5000 # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    useGlobalDataSourceStat: true  #合并多个DruidDataSource的监控数据(暂时不明白时什么意思，也没有测试出来)
    #cachePrepStmts: true  # 开启二级缓存
eureka:
  instance:
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
    prefer-ip-address: true     #访问路径可以显示IP地址
    lease-renewal-interval-in-seconds: 30 #该字段代表每2s像服务器发送一次心跳
    lease-expiration-duration-in-seconds: 90  #该字段代表如果6s内没有接收到客户端发过来的心跳，则会从实例中清除掉这个实例
  client:
    initial-instance-info-replication-interval-seconds: 6
    serviceUrl:
      defaultZone: http://lc.eureka.com:8761/eureka/,http://lc.eureka.com:8762/eureka/

## 该配置节点为独立的节点，有很多同学容易将这个配置放在spring的节点下，导致配置无法被识别
mybatis:
  mapper-locations: classpath:mapping/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: com.lc.clz.entity  # 注意：对应实体类的路径

  #pagehelper分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

#info需要显示的信息
info:
  app.name: lc-basic-service
  company.name: www.chenglezheng.com
  build.artifactId: ${project.artifactId}
  build.version: ${project.version}


logging:
  level:
    com.lc.clz.mapper: debug
server:
  port: 9000

management:
  endpoints:
    web:
      exposure:
        include: "*"   #2.0.X版本以上需要加这段配置，原因：以上版本没有暴露所有HTTP端口
  security:
    enabled: false  #关掉安全访问，否则/refresh没有访问权

security:
  oauth2:
    resource:
      id: lc-user-center
      user-info-uri: http://lc.auth.com:7000/user
      prefer-token-info: false