server:
  port: 8888
spring:
  application:
    name: lc-zuul
eureka:
  instance:
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
    lease-renewal-interval-in-seconds: 2 #该字段代表每2s像服务器发送一次心跳
    lease-expiration-duration-in-seconds: 6  #该字段代表如果6s内没有接收到客户端发过来的心跳，则会从实例中清除掉这个实例
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/,http://127.0.0.1:8762/eureka/
zuul:
  host:
    max-total-connections: 200
    max-per-route-connections: 20
  routes:
    lc-invoker:
      path: /lc/**