
#fdfs:
#  so-timeout: 1501
#  connect-timeout: 601
#  thumb-image:
#    width: 150
#    height: 150
#  tracker-list: 192.168.254.128:22122
#  tracker-server: 192.168.254.128:22122
eureka:
  client:
    service-url:
      defaultZone: http://lc.eureka.com:8761/eureka/,http://lc.eureka.com:8762/eureka/
spring:
  application:
    name: lc-upload
  datasource:
    name: lc-mybatis
    username: root
    url: jdbc:mysql://lc.mysql.com:3306/lc
    password: clz123456
    #url: jdbc:mysql://lc.mysql.com/south
    #password: root
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat,wall,log4j
    initialSize: 5
    maxActive: 20
    minIdle: 5
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20 
    connectionProperties :
      duird:
        stat:
          mergeSql: true
          slowSqlMillis: 5000
    useGlobalDataSourceStat: true
  thymeleaf:
    mode: LEGACYHTML5
    suffix: .html
  kafka:
    producer:
      bootstrap-servers: 127.0.0.1:9092
server:
  port: 9010